Vagrant.configure("2") do |config|

  config.vm.box = "gozma14/php5"

  config.vm.hostname = "zuba"
  config.vm.network "private_network", ip: "192.168.27.14"

  config.vm.synced_folder "..", "/vagrant"

  ###############################################################
  # cli/provision
  ###############################################################

  config.vm.provision "shell", path: "cli/provision.sh"
  config.vm.provision "shell", path: "cli/post-setup.sh", privileged: false

end
