<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle( 'Zuba' )->setSeparator( ' - ' )->setAutoEscape( FALSE ); ?>

    <?php echo $this->headMeta()
        ->appendName( 'viewport', 'width=device-width, initial-scale=1.0' )
        ->appendHttpEquiv( 'X-UA-Compatible', 'IE=edge' );
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink( array( 'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath( 'assets/images/favicon.ico' ) ) )
        ->appendStylesheet( 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' ); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->appendFile( 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array( 'conditional' => 'lt IE 9', ) )
        ->appendFile( 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array( 'conditional' => 'lt IE 9', ) ); ?>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url( 'home' ); ?>">Zuba</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#">@todo</a></li>
                <li><a href="#">@foo</a></li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

<div class="container">

    <?php echo $this->content; ?>

    <hr>

    <footer>
        <p>&copy; Zuba <?php echo date( 'Y' ); ?></p>
    </footer>

</div>

<!-- Inline Scripts -->
<?php echo $this->inlineScript()
    ->appendFile( 'https://code.jquery.com/jquery-1.11.3.min.js' )
    ->appendFile( 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' )
    ->appendFile( 'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.8.0/lodash.min.js' )
    ->appendFile( 'https://cdnjs.cloudflare.com/ajax/libs/knockout/3.3.0/knockout-min.js' ); ?>

</body>
</html>
