<?php /** @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle( 'Zuba' )->setSeparator( ' - ' )->setAutoEscape( FALSE ); ?>
    <?php echo $this->headMeta()->appendName( 'viewport', 'width=device-width, initial-scale=1.0' ); ?>
    <?php echo $this->headLink()->setStylesheet( 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' ); ?>
    <?php echo $this->headLink()->setStylesheet( $this->basePath( 'css/site.css' ) ); ?>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand" href="<?php echo $this->url( 'home' ); ?>">
                <i class="glyphicon glyphicon-home"></i>
                <span>Zuba</span>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->url( 'home' ); ?>">Home</a></li>
                <li><a href="<?php echo $this->url( '@todo' ); ?>">About</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->url( '@todo' ); ?>">@todo</a></li>
                <li><a href="<?php echo $this->url( '@foo' ); ?>">@foo</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">

    <?php echo $this->partial( 'partials/flash-messages.phtml' ); ?>

    <?php echo $this->content; ?>

    <hr>

    <footer>
        <p>&copy; Zuba <?php echo date( 'Y' ); ?></p>
    </footer>

</div>

<?php echo $this->inlineScript()->setFile( 'https://code.jquery.com/jquery-1.11.3.min.js' ); ?>
<?php echo $this->inlineScript()->setFile( 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' ); ?>

</body>
</html>
