<?php /** @var $this \Zend\View\Renderer\PhpRenderer */ ?>

<?php if ( $this->flashMessenger( 'success' ) ) : ?>

    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo $this->flashMessenger()->render( 'success' ); ?>
    </div>

<?php endif; ?>