<?php /** @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<?php /** @var $foo \Scaffold\Model\Foo */ ?>

<h1>Destroy @foo</h1>
<hr>

<div class="row">

    <div class="col-md-8">

        <table class="table table-hover table-bordered">

            <thead>
            <tr>
                <th>ID</th>
                <th><?php echo $foo->id; ?></th>
            </tr>
            </thead>

            <tbody>
            <tr>
                <th>@one</th>
                <td>@one</td>
            </tr>
            <tr>
                <th>@two</th>
                <td>@two</td>
            </tr>
            <tr>
                <th>@three</th>
                <td>@three</td>
            </tr>
            </tbody>

        </table>

    </div>

    <div class="col-md-4">

        <div class="panel panel-default">
            <div class="panel-body">

                <form
                    method="post"
                    action="<?php echo $this->url( '@foo' ); ?>">

                    <p>Are you sure about destroying @foo?</p>

                    <input type="hidden" name="id" value="<?php echo $foo->id; ?>">

                    <div class="pull-left"></div>

                    <div class="pull-right">

                        <input type="submit" class="btn btn-default" name="destroySubmit" value="No">
                        <input type="submit" class="btn btn-danger" name="destroySubmit" value="Yes">

                    </div>

                </form>

            </div>

        </div>

    </div>

</div>


