<?php /** @var $this \Zend\View\Renderer\PhpRenderer */ ?>

<h1>@foo</h1>
<hr>

<div class="row">

    <div class="col-md-12">

        <table class="table table-hover table-bordered">

            <thead>
            <tr>
                <th>ID</th>
                <th>@one</th>
                <th>@two</th>
                <th>@three</th>
                <th></th>
            </tr>
            </thead>

            <tbody>

            <?php foreach ( range( 1, 6 ) as $modelId ) : ?>

                <tr>
                    <td><?php echo $modelId; ?></td>
                    <td>@one</td>
                    <td>@two</td>
                    <td>@three</td>
                    <td>
                        <a href="<?php echo $this->url( '@foo', array( 'action' => 'show' ), array( 'query' => array( 'id' => $modelId ) ) ) ?>"><span class="glyphicon glyphicon-link"></span></a>
                        <a href="#"><span class="glyphicon glyphicon-edit"></span></a>
                        <a href="#"><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>

            <?php endforeach; ?>

            </tbody>

        </table>

    </div>

    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="pull-left"></div>

                <div class="pull-right">

                    <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> New @foo</a>

                </div>

            </div>
        </div>

    </div>

</div>