<?php /** @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<?php /** @var $foo \Scaffold\Model\Foo */ ?>
<?php /** @var $foos array */ ?>

<div class="page-header">
    <h1>@foo</h1>
</div>

<div class="row">

    <div class="col-md-12">

        <table class="table table-hover table-bordered">

            <thead>
            <tr>
                <th>ID</th>
                <th>@one</th>
                <th>@two</th>
                <th>@three</th>
                <th></th>
            </tr>
            </thead>

            <tbody>

            <?php foreach ( $foos as $foo ) : ?>

                <tr>
                    <td><?php echo $foo->id; ?></td>
                    <td>@one</td>
                    <td>@two</td>
                    <td>@three</td>
                    <td>

                        <a href="<?php echo $this->url( '@foo', array( 'action' => 'show' ), array( 'query' => array( 'id' => $foo->id ) ) ); ?>"><span
                                class="glyphicon glyphicon-link"></span></a>
                        <a href="#"><span class="glyphicon glyphicon-edit"></span></a>
                        <a href="<?php echo $this->url( '@foo', array( 'action' => 'destroy' ), array( 'query' => array( 'id' => $foo->id ) ) ); ?>"><span
                                class="glyphicon glyphicon-remove"></span></a>

                    </td>
                </tr>

            <?php endforeach; ?>

            </tbody>

        </table>

    </div>

    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="pull-left"></div>

                <div class="pull-right">

                    <a href="#" class="btn btn-primary">New @foo</a>

                </div>

            </div>
        </div>

    </div>

</div>