<?php /** @var $this \Zend\View\Renderer\PhpRenderer */ ?>

<div class="page-header">
    <h1>@todo</h1>
</div>

<div class="row">

    <div class="col-md-6">

        <h4>@todo</h4>

        <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

    </div>

    <div class="col-md-6">

        <h4>@todo</h4>

        <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

    </div>

</div>